CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED BY 'Underscore_08';
CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'Underscore_08';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'Underscore_08';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS `css_invest` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
FLUSH PRIVILEGES;
