const SEMANTIC_CONCEPT_CATEGORIES = [
  {
    key: "cash_position",
    label: "Cash Position",
    description: "Opening, closing, and net cash bridge concepts used to anchor cash balances.",
  },
  {
    key: "capital_activity",
    label: "Capital Activity",
    description: "Investor and partner capital flows such as subscriptions, redemptions, and distributions.",
  },
  {
    key: "income",
    label: "Income",
    description: "Recurring income and investment income concepts that contribute to results.",
  },
  {
    key: "expense",
    label: "Expense",
    description: "Operating, professional, and tax expense concepts.",
  },
  {
    key: "gains_losses",
    label: "Gains and Losses",
    description: "Realized, unrealized, and FX-related performance movements.",
  },
  {
    key: "payable_receivable",
    label: "Payables and Receivables",
    description: "Accrued and settlement-oriented balance sheet concepts tied to income or expenses.",
  },
  {
    key: "operating",
    label: "Operating",
    description: "Operating section concepts for cash-flow reporting.",
  },
  {
    key: "investing",
    label: "Investing",
    description: "Investing section concepts for cash-flow reporting.",
  },
  {
    key: "financing",
    label: "Financing",
    description: "Financing section concepts for cash-flow reporting.",
  },
  {
    key: "equity",
    label: "Equity",
    description: "Equity bridge concepts that are reusable across capital activity and NAV reporting.",
  },
  {
    key: "other",
    label: "Other",
    description: "Fallback concepts that do not yet fit a narrower canonical bucket.",
  },
]

const EXPECTED_SIGNS = ["positive", "negative", "either"]
const EXPECTED_BALANCE_TYPES = ["debit", "credit", "either", "memo"]
const AGGREGATION_BEHAVIORS = ["sum", "subtract", "derived", "opening_balance", "closing_balance"]
const STATEMENT_TYPES = ["cash_flow", "nav", "capital_activity", "pnl", "balance_sheet", "generic"]

const SEMANTIC_CONCEPT_TAXONOMY = [
  {
    key: "opening_cash",
    label: "Opening Cash",
    description: "Opening cash balance at the start of the reporting period.",
    category: "cash_position",
    subcategory: "cash_bridge",
    expectedSign: "positive",
    expectedBalanceType: "debit",
    aggregationBehavior: "opening_balance",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["cash at beginning", "beginning cash", "opening balance", "cash at start of period"],
    examples: ["Cash at beginning of period", "Opening cash balance"],
    sortOrder: 10,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "closing_cash",
    label: "Closing Cash",
    description: "Closing cash balance at the end of the reporting period.",
    category: "cash_position",
    subcategory: "cash_bridge",
    expectedSign: "positive",
    expectedBalanceType: "debit",
    aggregationBehavior: "closing_balance",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["cash at end", "ending cash", "closing balance", "cash at end of period"],
    examples: ["Cash at end of period", "Closing cash balance"],
    sortOrder: 20,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "net_change_in_cash",
    label: "Net Change in Cash",
    description: "Derived net increase or decrease in cash for the reporting period.",
    category: "cash_position",
    subcategory: "cash_bridge",
    expectedSign: "either",
    expectedBalanceType: "memo",
    aggregationBehavior: "derived",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["net increase in cash", "net decrease in cash", "change in cash"],
    examples: ["Net increase in cash", "Net change in cash and cash equivalents"],
    sortOrder: 30,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "subscriptions",
    label: "Subscriptions",
    description: "Investor subscriptions and capital inflows into the fund.",
    category: "capital_activity",
    subcategory: "investor_flows",
    expectedSign: "positive",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "capital_activity",
    dimensionsAllowed: ["period", "entity", "currency", "share_class"],
    synonyms: ["capital contributions", "investor subscriptions", "contributions"],
    examples: ["Subscriptions", "Capital contributions received"],
    sortOrder: 40,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "capital_calls",
    label: "Capital Calls",
    description: "Capital called from investors or limited partners.",
    category: "capital_activity",
    subcategory: "investor_flows",
    expectedSign: "positive",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "capital_activity",
    dimensionsAllowed: ["period", "entity", "currency", "share_class"],
    synonyms: ["capital called", "drawdowns", "draw downs"],
    examples: ["Capital calls", "Investor drawdowns"],
    sortOrder: 50,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "redemptions",
    label: "Redemptions",
    description: "Investor redemptions and capital outflows from the fund.",
    category: "capital_activity",
    subcategory: "investor_flows",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "capital_activity",
    dimensionsAllowed: ["period", "entity", "currency", "share_class"],
    synonyms: ["capital withdrawals", "withdrawals", "investor redemptions"],
    examples: ["Redemptions", "Capital withdrawn by investors"],
    sortOrder: 60,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "distributions",
    label: "Distributions",
    description: "Cash or capital distributions paid to investors.",
    category: "capital_activity",
    subcategory: "investor_flows",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "capital_activity",
    dimensionsAllowed: ["period", "entity", "currency", "share_class"],
    synonyms: ["partner distributions", "investor distributions", "cash distributions"],
    examples: ["Distributions", "Distributions paid"],
    sortOrder: 70,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "realized_gain_loss",
    label: "Realized Gain or Loss",
    description: "Realized gain or loss recognized on disposals or settlements.",
    category: "gains_losses",
    subcategory: "realized",
    expectedSign: "either",
    expectedBalanceType: "either",
    aggregationBehavior: "sum",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency", "investment"],
    synonyms: ["realized gain", "realized loss", "realized pnl"],
    examples: ["Realized gain/(loss)", "Net realized gain or loss"],
    sortOrder: 80,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "unrealized_gain_loss",
    label: "Unrealized Gain or Loss",
    description: "Unrealized mark-to-market gain or loss recognized for the period.",
    category: "gains_losses",
    subcategory: "unrealized",
    expectedSign: "either",
    expectedBalanceType: "either",
    aggregationBehavior: "sum",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency", "investment"],
    synonyms: ["unrealized gain", "unrealized loss", "mark to market"],
    examples: ["Unrealized gain/(loss)", "Net change in unrealized appreciation"],
    sortOrder: 90,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "fx_gain_loss",
    label: "FX Gain or Loss",
    description: "Foreign exchange gain or loss recognized on cash, positions, or settlements.",
    category: "gains_losses",
    subcategory: "foreign_exchange",
    expectedSign: "either",
    expectedBalanceType: "either",
    aggregationBehavior: "sum",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["foreign exchange gain", "foreign exchange loss", "currency gain", "currency loss"],
    examples: ["FX gain/(loss)", "Foreign exchange translation gain or loss"],
    sortOrder: 100,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "interest_income",
    label: "Interest Income",
    description: "Interest income earned on cash, debt instruments, or receivables.",
    category: "income",
    subcategory: "investment_income",
    expectedSign: "positive",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency", "investment"],
    synonyms: ["interest earned", "coupon income"],
    examples: ["Interest income", "Interest earned on cash balances"],
    sortOrder: 110,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "dividend_income",
    label: "Dividend Income",
    description: "Dividend income recognized from investments.",
    category: "income",
    subcategory: "investment_income",
    expectedSign: "positive",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency", "investment"],
    synonyms: ["dividends received", "distribution income"],
    examples: ["Dividend income", "Dividends received"],
    sortOrder: 120,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "receivable_income",
    label: "Receivable Income",
    description: "Receivable income balances such as accrued interest or dividend receivables.",
    category: "payable_receivable",
    subcategory: "income_receivables",
    expectedSign: "positive",
    expectedBalanceType: "debit",
    aggregationBehavior: "sum",
    statementType: "balance_sheet",
    dimensionsAllowed: ["period", "entity", "currency", "counterparty"],
    synonyms: ["income receivable", "interest receivable", "dividend receivable"],
    examples: ["Accrued income receivable", "Interest receivable"],
    sortOrder: 130,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "management_fees",
    label: "Management Fees",
    description: "Management fee expense recognized or settled for the period.",
    category: "expense",
    subcategory: "fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["management fee", "base management fee"],
    examples: ["Management fees", "Investment manager fees"],
    sortOrder: 140,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "performance_fees",
    label: "Performance Fees",
    description: "Performance or incentive fee expense recognized or settled for the period.",
    category: "expense",
    subcategory: "fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["incentive fee", "performance allocation"],
    examples: ["Performance fees", "Incentive fees"],
    sortOrder: 150,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "custody_fees",
    label: "Custody Fees",
    description: "Custodian or safekeeping fee expense.",
    category: "expense",
    subcategory: "service_fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["custodian fees", "safekeeping fees"],
    examples: ["Custody fees", "Custodian service fees"],
    sortOrder: 160,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "administration_fees",
    label: "Administration Fees",
    description: "Fund administration fee expense.",
    category: "expense",
    subcategory: "service_fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["admin fees", "fund administration fees"],
    examples: ["Administration fees", "Fund admin fees"],
    sortOrder: 170,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "audit_fees",
    label: "Audit Fees",
    description: "Audit and assurance fee expense.",
    category: "expense",
    subcategory: "professional_fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["audit expense", "audit and assurance fees"],
    examples: ["Audit fees", "External audit expense"],
    sortOrder: 180,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "legal_fees",
    label: "Legal Fees",
    description: "Legal and compliance professional fee expense.",
    category: "expense",
    subcategory: "professional_fees",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["legal expense", "compliance fees"],
    examples: ["Legal fees", "Professional legal expenses"],
    sortOrder: 190,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "tax_expense",
    label: "Tax Expense",
    description: "Tax expense recognized for the reporting period.",
    category: "expense",
    subcategory: "tax",
    expectedSign: "negative",
    expectedBalanceType: "debit",
    aggregationBehavior: "subtract",
    statementType: "pnl",
    dimensionsAllowed: ["period", "entity", "currency", "jurisdiction"],
    synonyms: ["income tax expense", "withholding tax expense"],
    examples: ["Tax expense", "Income tax provision"],
    sortOrder: 200,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "accrued_expenses",
    label: "Accrued Expenses",
    description: "Accrued operating expenses not yet paid.",
    category: "payable_receivable",
    subcategory: "expense_accruals",
    expectedSign: "negative",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "balance_sheet",
    dimensionsAllowed: ["period", "entity", "currency", "counterparty"],
    synonyms: ["expense accruals", "accrued liabilities"],
    examples: ["Accrued expenses", "Accrued management fees"],
    sortOrder: 210,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "payable_expenses",
    label: "Payable Expenses",
    description: "Expense-related payables such as management, admin, or professional fee payables.",
    category: "payable_receivable",
    subcategory: "expense_payables",
    expectedSign: "negative",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "balance_sheet",
    dimensionsAllowed: ["period", "entity", "currency", "counterparty"],
    synonyms: ["expenses payable", "fee payable", "accounts payable"],
    examples: ["Expenses payable", "Management fees payable"],
    sortOrder: 220,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "distributions_payable",
    label: "Distributions Payable",
    description: "Declared distributions that are payable but not yet settled.",
    category: "payable_receivable",
    subcategory: "investor_payables",
    expectedSign: "negative",
    expectedBalanceType: "credit",
    aggregationBehavior: "sum",
    statementType: "balance_sheet",
    dimensionsAllowed: ["period", "entity", "currency", "share_class"],
    synonyms: ["distribution payable", "investor distributions payable"],
    examples: ["Distributions payable", "Declared distributions unpaid"],
    sortOrder: 230,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "operating_cash_flow",
    label: "Operating Cash Flow",
    description: "Operating section net cash flow for the reporting period.",
    category: "operating",
    subcategory: "cash_flow_summary",
    expectedSign: "either",
    expectedBalanceType: "memo",
    aggregationBehavior: "sum",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["net cash from operating activities", "operating activities"],
    examples: ["Net cash provided by operating activities", "Operating cash flow"],
    sortOrder: 240,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "investing_cash_flow",
    label: "Investing Cash Flow",
    description: "Investing section net cash flow for the reporting period.",
    category: "investing",
    subcategory: "cash_flow_summary",
    expectedSign: "either",
    expectedBalanceType: "memo",
    aggregationBehavior: "sum",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["net cash from investing activities", "investing activities"],
    examples: ["Net cash used in investing activities", "Investing cash flow"],
    sortOrder: 250,
    metadata: { seeded_family: "fund_accounting" },
  },
  {
    key: "financing_cash_flow",
    label: "Financing Cash Flow",
    description: "Financing section net cash flow for the reporting period.",
    category: "financing",
    subcategory: "cash_flow_summary",
    expectedSign: "either",
    expectedBalanceType: "memo",
    aggregationBehavior: "sum",
    statementType: "cash_flow",
    dimensionsAllowed: ["period", "entity", "currency"],
    synonyms: ["net cash from financing activities", "financing activities"],
    examples: ["Net cash provided by financing activities", "Financing cash flow"],
    sortOrder: 260,
    metadata: { seeded_family: "fund_accounting" },
  },
]

function toDatabaseConcept(definition, timestamp = new Date()) {
  return {
    id: definition.id,
    stable_key: definition.key,
    label: definition.label,
    description: definition.description,
    category: definition.category,
    subcategory: definition.subcategory || null,
    expected_sign: definition.expectedSign || null,
    expected_balance_type: definition.expectedBalanceType || null,
    aggregation_behavior: definition.aggregationBehavior,
    statement_type: definition.statementType,
    dimensions_allowed_json: definition.dimensionsAllowed || [],
    synonyms_json: definition.synonyms || [],
    examples_json: definition.examples || [],
    sort_order: Number.isFinite(Number(definition.sortOrder)) ? Number(definition.sortOrder) : 0,
    metadata_json: definition.metadata || null,
    is_active: definition.active !== false,
    created_at: timestamp,
    updated_at: timestamp,
  }
}

module.exports = {
  SEMANTIC_CONCEPT_CATEGORIES,
  EXPECTED_SIGNS,
  EXPECTED_BALANCE_TYPES,
  AGGREGATION_BEHAVIORS,
  STATEMENT_TYPES,
  SEMANTIC_CONCEPT_TAXONOMY,
  toDatabaseConcept,
}
